### PR TITLE
Jg update master

### PR DESCRIPTION
**Pull request by jongough**
Attempt to move jsoncpp to libs directory. Don't merge but do try out any successful builds

### CODE REVIEW

**Comment by rgleason** [comment]
It works like a charm under Windows10, with grib_pi and climatology.
I should check the use of boundaries from ocpn_draw next.
Does the fact that we are not using json validation mean that we do not need 
extsrc/json-schema-validator  and extincludee/nolohmann?

and would the same apply to watchdog_pi which uses a lot of ODAPI for alarms.

**Comment by rgleason** [comment]
I've checked the boundary function and it also works well.
Screenshot (137)
Screenshot (138)
Screenshot (136)

**Comment by rgleason** [comment]
Should I merge it?

**Comment by jongough** [comment]
I am moving more of the libs so there will be a couple more pushes to complete the process. So hang fire for the moment.

**Comment by rgleason** [comment]
ok, i'll check operation with linux later.

**Comment by jongough** [comment]
I think this can now be merged. I have done a bit of a clean up of the main cmake file and moved the libs to the 'libs' directory.

**Comment by rgleason** [comment]
I wonder if zlib1.lib should be in buildwin, is that appropriate?
target_link_libraries(${PACKAGE_NAME} "${CMAKE_SOURCE_DIR}/buildwin/zlib1.lib")

**Comment by jongough** [comment]
This appears to be something special that Sean added to handle weather data compression so I would leave it as it is. The plugin has been converted to using frontend2 and the new 'libs' process that is being used. I think it should have been in 'extinclude' as it is used as is from a third party, but.... It does not harm where it is and the plugin builds OK.

**Comment by rgleason** [comment]
Thanks very much!

**Pull request merged**
