### PR TITLE
Remove pidc.cpp reference to DrawPolygonTessellated as used glu tesse…

### PR DESCRIPTION
**Pull request by jongough**
…llation and not really used

### CODE REVIEW

**Comment by rgleason** [comment]
OCPN uses glu based libtess, whereas Weather_Routing uses libtess2. I can put in the 'standard' OCPN lib if you want.

Sounds good to me if it can be done relatively easily and doesn't create trouble for you.

I merged it and there seems to be an issue with some of the builds.
For example with trusty.  PluginInstall.cmake line 164 


```
-- Processing PluginJSON.cmake
-- PROJECT_SOURCE_DIR: /home/circleci/project
-- Add Library weather_routing_pi_LIB_PLUGINJSON
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- *** Will install to /usr/local  ***
-- PREFIX_PARENTLIB: lib/opencpn
CMake Error at cmake/PluginInstall.cmake:164 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "weather_routing_pi".
Call Stack (most recent call first):
  CMakeLists.txt:424 (INCLUDE)
```

This is

```
if(UNIX AND NOT APPLE)
  set(PREFIX_PARENTDATA ${PREFIX_DATA}/${PARENT})
  set(PREFIX_PARENTLIB ${PREFIX_LIB}/${PARENT})
  message(STATUS "PREFIX_PARENTLIB: ${PREFIX_PARENTLIB}")
  install(     <-----LINE 164
    TARGETS ${PACKAGE_NAME}
    RUNTIME
    LIBRARY DESTINATION ${PREFIX_PARENTLIB})
```

**Comment by jongough** [comment]
Interesting. My build on my frontend2_jg all went OK until the cloudsmith step where if failed due to not having permissions to upload. The error you are getting is one I did see while doing testing, I just have to remember what it was that caused it.

**Comment by jongough** [comment]
I found the problem. You still had 'STATIC'  on line 376 (this was a test I did a while ago) but it should be 'SHARED', I have pushed this to my repository and if it builds OK (apart from cloudsmith) will create a pull request

**Comment by rgleason** [comment]
Thanks Jon, should have thought of that.

**Pull request merged**
