### PR TITLE
Tidy up GUI

### PR DESCRIPTION
**Pull request by ThomTrab**
As I already did for the WeatherFax Plugin, here is a PR for GUI improvement of the Weather Routing plugin:
* Increase wxSpinCtrl min width to avoid clipping under Linux
* Improve padding and panel organization
* Fix polar, crossover and plot graph : clear window before drawing

### CODE REVIEW

**Comment by rgleason** [comment]
ThomTraub, thank you!  You've gotten good at this.

**Comment by ThomTrab** [comment]
Your welcome.

Yes, indeed, I start to know my way around the tool. I started doing the same on the Grib plugin, but that seem to be another story. The layout of the plugin doesn't seem to be done fully with wxFormBuilder.

**Comment by rgleason** [comment]
Yes, some of them were then adjusted by hand I believe

**Comment by rgleason** [comment]
@ThomTraub
Please see https://github.com/rgleason/weather_routing_pi/issues/68

**Pull request merged**
